### ISSUE TITLE
Adding distributed testing for inference server

### ISSUE THREAD

**Issue by jackapbutler** [LAION-AI/Open-Assistant#1621]
# Overview 
We want to test the dockerised inference-server under different stress conditions such as;
1. Load testing - handling many concurrent of users
2. Latency testing - speed of response to users 
3. ...

This should inform changes to the inference server as it can help diagnose bottlenecks in the backend. It also gives us a better idea on the compute requirements for hosting a worker or inference server node in different conditions.

# Tasks
- [ ] Implement basic tests for starting conversations and sending messages to the inference server through the `/chat` and `/chat/{chat_id}/message` endpoints
- [ ] Perform these distributed tests for different amounts of concurrent users & fix any logical problems that arise from the stress tests
- [ ] Expand the distributed tests to the `/work` and `/generate_stream` and other endpoints in the application
- [ ] Expand to more complex user scenarios or different user profiles
- [ ] Deploy distributed tests on a standardised compute setup rather than on a local laptop

# Context
@yk suggested I work on this and I'm a research engineer at Faculty (https://faculty.ai/) committing almost full time to OS contributions for the foreseeable future

**Comment by jackapbutler** [comment]
self-assign

**Comment by jackapbutler** [comment]
Hey @olliestanley, no sorry I won't be able to commit to this now.

**Comment by olliestanley** [comment]
No problem :)
