### ISSUE TITLE
Discord bot issue list

### ISSUE THREAD

**Issue by AlexanderHOtt** [LAION-AI/Open-Assistant#231]
This is a list of features that still need to be implemented for the discord bot. Feel free ask for more detail on a specific task.

## Fixes

- [x] make sure a user can only do 1 task a time (#265)
- [x] bot can start work from DMs (#267)
- [x] write better docs for starters (#253)

## Bot

- [x] proper error handling (#235)
- [ ] backend text labeling (#43)
- [x] docker setup (#292)
- [x] add a way to track ram / cpu usage for future optimizing (#269)
- [x] multi-message (#1056)

## Quality of life / UI

- [x] improve bot message wording (#318)
- [x] move all user facing messages to a central place (#318)
- [x] `/help` (#399)
- [x] `/tutorial` (#399)
- [x] refactor API client to `oasst-shared` folder

## Waiting on

- [ ] leaderboard / points

**Comment by AlexanderHOtt** [comment]
> I would want to work on docker setup and after done on ram/cpu usage tracking

Go ahead with the docker setup (you might need to add code to create the sqlite file if it doesn't exist), but I want to handle the CPU/memory tracking because that goes into monitoring cache calls (which I expect you don't know because it isn't documented)

**Comment by andreaskoepf** [comment]
api-client to oaast-shared is tracked here: https://github.com/LAION-AI/Open-Assistant/issues/243

**Comment by andreaskoepf** [comment]
Testing/usability feeedback:

1. Have you tested with longer, e.g. 1000 character prompts/conversations and conversations of depth 3 (e.g. after User and Assistant both said something 2x)? If I add a reaction to the bot message for testing it still looks like one big message... (long messages will exceed the discord size limit and in the log channel won't allow individual reactions.)
2. Display the prompt/conversation-reply submitted by the user in the log-channel so that it becomes publicly visible... currently only general stats/activity is shown. Post the individual messages of the conversation as separate discrod-messages so that (other) users could respond to them individually via emoji reactions.
3. The help menu with step-through next >, < prev buttons is in my opinion not helpful, please print one or multiple messages with available commands and some general information.
4. The timeout of the private bot-session is set too low, please make it configurable in seconds, default to 600.
5. Please add a colon at the end of "Enter response here:"
6. Please move task instructions like "Reply with the numbers of best to worst replies separated by commas (example: '4,1,3,2')" to the bottom.. e.g. below the ranking-options, so that the comma delimited example is visible just above the discord-input text-box at the bottom of the screen.

**Comment by AlexanderHOtt** [comment]
> Testing/usability feeedback:
> 
> 1. Have you tested with longer, e.g. 1000 character prompts/conversations and conversations of depth 3 (e.g. after User and Assistant both said something 2x)? If I add a reaction to the bot message for testing it still looks like one big message... (long messages will exceed the discord size limit and in the log channel won't allow individual reactions.)
> 2. Display the prompt/conversation-reply submitted by the user in the log-channel so that it becomes publicly visible... currently only general stats/activity is shown. Post the individual messages of the conversation as separate discrod-messages so that (other) users could respond to them individually via emoji reactions.
> 3. The help menu with step-through next >, < prev buttons is in my opinion not helpful, please print one or multiple messages with available commands and some general information.
> 4. The timeout of the private bot-session is set too low, please make it configurable in seconds, default to 600.
> 5. Please add a colon at the end of "Enter response here:"
> 6. Please move task instructions like "Reply with the numbers of best to worst replies separated by commas (example: '4,1,3,2')" to the bottom.. e.g. below the ranking-options, so that the comma delimited example is visible just above the discord-input text-box at the bottom of the screen.

4-6 fixed in #357

**Comment by andreaskoepf** [comment]
Closing all old discord bot issues. Discord data collection never took off. It might be more viable to develop a discord bot that communicates with the inference system.
