### ISSUE TITLE
Message Drafts Additional Feature Tracking

### ISSUE THREAD

**Issue by someone13574** [LAION-AI/Open-Assistant#3279]
This is an issue for tracking a few additional features which should be added for message drafts

- [ ] Disable all messages drafts under high load (requires fixing inaccurate queue first #2822 )
- [ ] Add toggle so users can choose to generate drafts when they feel fit instead of only on a message regeneration (requires adding disable under load first)
- [ ] Make sure message evaluations are removed / not collected when a chat is deleted or the user opts-out of data collection for that chat.
- [ ] If the user opts-out of data collection, simply don't generate drafts as they are primarily for collecting data.
