### ISSUE TITLE
Reimplement discord bot using hikari

### ISSUE THREAD

**Issue by andreaskoepf** [LAION-AI/Open-Assistant#95]
Rewrite the discord-bot using [hikari](https://docs.hikari-py.dev/en/latest/).

**Comment by AlexanderHOtt** [comment]
I'll do this

**Comment by shroominic** [comment]
Hey I want to help with the discord bot and maybe we should decide about the framework because there is (in my opinion) a better one: (Pycord)[https://github.com/Pycord-Development/pycord]

They just released V3 which is structured really good. In addition it is forked from discord.py so we can reuse some code.

**Comment by AlexanderHOtt** [comment]
Current work is in #135

**Comment by AlexanderHOtt** [comment]
# TODO

## Bot

- [ ] proper error handling
- [ ] backend text labeling
- [ ] docker setup (maybe?)

## Quality of life / UI

- [ ] improve bot message wording
- [ ] switch most (if not all) bot messages to embeds
- [ ] move all user facing messages (embeds) to a central place
- [ ] add better images to embeds
- [ ] `/help`
- [ ] `/tutorial`
- [ ] refactor API client to `oasst-shared` folder

## Waiting on

- [ ] leaderboard / points
